# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chartdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('direction', models.IntegerField()),
                ('Xaxisa', models.IntegerField()),
                ('Xaxisb', models.IntegerField()),
                ('Yaxis', models.IntegerField()),
                ('Alane', models.IntegerField()),
                ('Blane', models.IntegerField()),
                ('Clane', models.IntegerField()),
                ('Dlane', models.IntegerField()),
            ],
        ),
    ]
