# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-15 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='I023',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('inteid', models.IntegerField(blank=True, null=True)),
                ('direction', models.IntegerField(blank=True, null=True)),
                ('lane', models.IntegerField(blank=True, null=True)),
                ('carplate', models.CharField(blank=True, max_length=11, null=True)),
                ('passtime', models.DateTimeField(blank=True, null=True)),
                ('traveltime', models.IntegerField(blank=True, null=True)),
                ('upinteid', models.IntegerField(blank=True, null=True)),
                ('updirection', models.IntegerField(blank=True, null=True)),
                ('uplane', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'i023',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='I024',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inteid', models.IntegerField(blank=True, null=True)),
                ('direction', models.IntegerField(blank=True, null=True)),
                ('lane', models.IntegerField(blank=True, null=True)),
                ('carplate', models.CharField(blank=True, max_length=11, null=True)),
                ('passtime', models.DateTimeField(blank=True, null=True)),
                ('traveltime', models.IntegerField(blank=True, null=True)),
                ('upinteid', models.IntegerField(blank=True, null=True)),
                ('updirection', models.IntegerField(blank=True, null=True)),
                ('uplane', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'i024',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='I055',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inteid', models.IntegerField(blank=True, null=True)),
                ('direction', models.IntegerField(blank=True, null=True)),
                ('lane', models.IntegerField(blank=True, null=True)),
                ('carplate', models.CharField(blank=True, max_length=11, null=True)),
                ('passtime', models.DateTimeField(blank=True, null=True)),
                ('traveltime', models.IntegerField(blank=True, null=True)),
                ('upinteid', models.IntegerField(blank=True, null=True)),
                ('updirection', models.IntegerField(blank=True, null=True)),
                ('uplane', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'i055',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='I056',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inteid', models.IntegerField(blank=True, null=True)),
                ('direction', models.IntegerField(blank=True, null=True)),
                ('lane', models.IntegerField(blank=True, null=True)),
                ('carplate', models.CharField(blank=True, max_length=11, null=True)),
                ('passtime', models.DateTimeField(blank=True, null=True)),
                ('traveltime', models.IntegerField(blank=True, null=True)),
                ('upinteid', models.IntegerField(blank=True, null=True)),
                ('updirection', models.IntegerField(blank=True, null=True)),
                ('uplane', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'i056',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='I057',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inteid', models.IntegerField(blank=True, null=True)),
                ('direction', models.IntegerField(blank=True, null=True)),
                ('lane', models.IntegerField(blank=True, null=True)),
                ('carplate', models.CharField(blank=True, max_length=11, null=True)),
                ('passtime', models.DateTimeField(blank=True, null=True)),
                ('traveltime', models.IntegerField(blank=True, null=True)),
                ('upinteid', models.IntegerField(blank=True, null=True)),
                ('updirection', models.IntegerField(blank=True, null=True)),
                ('uplane', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'i057',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='I058',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('inteid', models.IntegerField(blank=True, null=True)),
                ('direction', models.IntegerField(blank=True, null=True)),
                ('lane', models.IntegerField(blank=True, null=True)),
                ('carplate', models.CharField(blank=True, max_length=11, null=True)),
                ('passtime', models.DateTimeField(blank=True, null=True)),
                ('traveltime', models.IntegerField(blank=True, null=True)),
                ('upinteid', models.IntegerField(blank=True, null=True)),
                ('updirection', models.IntegerField(blank=True, null=True)),
                ('uplane', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'i058',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='I075',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inteid', models.IntegerField(blank=True, null=True)),
                ('direction', models.IntegerField(blank=True, null=True)),
                ('lane', models.IntegerField(blank=True, null=True)),
                ('carplate', models.CharField(blank=True, max_length=11, null=True)),
                ('passtime', models.DateTimeField(blank=True, null=True)),
                ('traveltime', models.IntegerField(blank=True, null=True)),
                ('upinteid', models.IntegerField(blank=True, null=True)),
                ('updirection', models.IntegerField(blank=True, null=True)),
                ('uplane', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'i075',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='I077',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('inteid', models.IntegerField(blank=True, null=True)),
                ('direction', models.IntegerField(blank=True, null=True)),
                ('lane', models.IntegerField(blank=True, null=True)),
                ('carplate', models.CharField(blank=True, max_length=11, null=True)),
                ('passtime', models.DateTimeField(blank=True, null=True)),
                ('traveltime', models.IntegerField(blank=True, null=True)),
                ('upinteid', models.IntegerField(blank=True, null=True)),
                ('updirection', models.IntegerField(blank=True, null=True)),
                ('uplane', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'i077',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='I089',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('inteid', models.IntegerField(blank=True, null=True)),
                ('direction', models.IntegerField(blank=True, null=True)),
                ('lane', models.IntegerField(blank=True, null=True)),
                ('carplate', models.CharField(blank=True, max_length=11, null=True)),
                ('passtime', models.DateTimeField(blank=True, null=True)),
                ('traveltime', models.IntegerField(blank=True, null=True)),
                ('upinteid', models.IntegerField(blank=True, null=True)),
                ('updirection', models.IntegerField(blank=True, null=True)),
                ('uplane', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'i089',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tsclane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField(blank=True, null=True)),
                ('feature', models.IntegerField(blank=True, null=True)),
                ('attribute', models.IntegerField(blank=True, null=True)),
                ('movement', models.IntegerField(blank=True, null=True)),
                ('detector', models.IntegerField(blank=True, null=True)),
                ('direction', models.IntegerField(blank=True, null=True)),
                ('intersectionid', models.IntegerField(blank=True, db_column='intersectionId', null=True)),
            ],
            options={
                'db_table': 'tsclane',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='sectordiagram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originyear', models.IntegerField()),
                ('originmonth', models.IntegerField()),
                ('originday', models.IntegerField()),
                ('originhour', models.IntegerField()),
                ('endyear', models.IntegerField()),
                ('endmonth', models.IntegerField()),
                ('endday', models.IntegerField()),
                ('endhour', models.IntegerField()),
            ],
        ),
    ]
